CREATE PROCEDURE PR_INS_TB_XPTO_OS


   @TITULO_SERV VARCHAR(150)
  ,@CNPJ_CLI NUMERIC (14,0)
  ,@NOME_CLI VARCHAR(150)
  ,@CPF_PREST NUMERIC (11,0)
  ,@NOME_PREST VARCHAR(150)
  ,@DATA_SERV  DATE
  ,@VALOR_SERV NUMERIC (13,2)

AS 

INSERT INTO TB_XPTO_OS
  (
   TITULO_SERV
  ,CNPJ_CLI
  ,NOME_CLI
  ,CPF_PREST
  ,NOME_PREST
  ,DATA_SERV
  ,VALOR_SERV
  )
  VALUES
  (
   @TITULO_SERV
  ,@CNPJ_CLI
  ,@NOME_CLI
  ,@CPF_PREST
  ,@NOME_PREST
  ,@DATA_SERV
  ,@VALOR_SERV
  )
